-- Aula Privilégios Padrão

GRANT USAGE ON SCHEMA meu_esquema TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA meu_esquema GRANT SELECT, REFERENCES ON TABLES TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA meu_esquema GRANT ALL ON TABLES TO vitor WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA meu_esquema GRANT SELECT, UPDATE ON SEQUENCES TO public;

ALTER DEFAULT PRIVILEGES IN SCHEMA meu_esquema GRANT ALL ON FUNCTIONS TO vitor WITH GRANT OPTION;


-- Links: https://www.postgresql.org/docs/current/static/sql-alterdefaultprivileges.html
