-- Aula Roles


CREATE ROLE joao LOGIN PASSWORD '123456' CREATEDB VALID UNTIL 'infinity';

CREATE ROLE regina LOGIN PASSWORD '123456' SUPERUSER VALID UNTIL '2022-1-1 00:00';

DROP ROLE maria;

CREATE ROLE grupo1 INHERIT;

GRANT grupo1 TO joao;

GRANT grupo1 TO regina;
